[package]

name = "asn1"
version = "0.0.0"
authors = ["Daniel Hackney <dan@haxney.org>"]

[[lib]]

name = "asn1"
path = "src/lib.rs"

[dependencies.peg]

git = "https://github.com/kevinmehall/rust-peg.git"
